// src/app/enums/ciudad.enum.ts
export enum Ciudad {
  MEDELLIN = 'Medellín',
  ARAUCA = 'Arauca',
  BARRANQUILLA = 'Barranquilla',
  CARTAGENA = 'Cartagena',
  TUNJA = 'Tunja',
  MANIZALES = 'Manizales',
  FLORENCIA = 'Florencia',
  YOPAL = 'Yopal',
  POPAYAN = 'Popayán',
  VALLEDUPAR = 'Valledupar',
  QUIBDO = 'Quibdó',
  MONTERIA = 'Montería',
  BOGOTA = 'Bogotá',
  INIRIDA = 'Inírida',
  SAN_JOSE_DEL_GUAVIARE = 'San José del Guaviare',
  NEIVA = 'Neiva',
  RIOHACHA = 'Riohacha',
  SANTA_MARTA = 'Santa Marta',
  VILLAVICENCIO = 'Villavicencio',
  PASTO = 'Pasto',
  CUCUTA = 'Cúcuta',
  MOCOA = 'Mocoa',
  ARMENIA = 'Armenia',
  PEREIRA = 'Pereira',
  SAN_ANDRES = 'San Andrés',
  BUCARAMANGA = 'Bucaramanga',
  SINCELEJO = 'Sincelejo',
  IBAGUE = 'Ibagué',
  CALI = 'Cali',
  MITU = 'Mitú',
  PUERTO_CARREÑO = 'Puerto Carreño'
}
